<?php
/* Admin constant and messages */
define('ROLE_ADMIN',1);
define('SITE_TITLE','spayc');
$config =array();
$config['CMS']= [
                  1=>'Access denied.',
                  2=>'Email or password is incorrect.',
                  3=>'Successfully saved.',
                  4=>'Successfully updated.',
                  5=>'Email does not exist.',
                  6=>'Unable to save. Please try again.',
                  7=>'We have sent the reset password link to your registered email.',
                  8=>'Successfully deleted.',
                  9=>'Unable to delete. Please try again.',
                  10=>'Please complete all the required fields.',
                  11=>'Image height and width should be 54 x 54.',
                  12=>'Already exist. Please try again with another name.',
                  13=>'Please select at least one organization.',
                  14=>'Please complete all the required fields.',
                ];
$config['ERRORANDSUCCESSMSG'] = [
    1=>'You log out successfully.',
    2=>'Please enter your email.',
    3=>'Please enter your valid email.',
    4=>'Please enter your password.',    
    5=>'Password must contain a minimum of 8 characters and 1 number.',
    6=>'Oops! The work email or password is incorrect.',
    7=>'Please enter an email address to reset your password.',
    8=>'This email address is not associated with any account.',
    9=>'Thank you, a temporary password has been sent to your email.',
    10=>'Please enter your current password.',
    11=>'Current password and new password cannot be same.',
    12=>'Oops! New passwords do not match.',
    13=>'Password must have 8 characters and 1 number.',
    14=>'Please create a previously unused password.',
    15=>'Are you sure you want to leave this section without responding or click PROCEED WITHOUT COMPLETING THIS STAGE.',
    16=>'Oops! new password and confirm password does not match.',
    17=>'Please enter old password.',
    18=>'Please enter new password.',
    19=>'An unexpected database error occurred. Please try again later.',
    20=>'Please enter confirm password.',
    21=>'Your password reset successfully.',
    22=>'Logged out successfully.',
    23=>'No search results found.',
    24=>'Timeout, Please try once again.',
    25=>'Error in connection.',   
    26=>'Email id already exists.',   
    27=>'Your password has been changed successfully.',
    28=>'Old password does not match.',
    29=>'Please make sure to fill out all the required fields correctly',  
    30=>'Blank space not allowed.',        
    31=>'Please enter a numeric value only.', 
    32=>'Invalid email or password.',   
    33=>'Please enter your email and password.',   
    34=>'Oops! Current passwords do not match.',
    35=>'Your password has been changed successfully.',
    36=>'Account not found. Please read email carefully and try again',
    37=>'Invalid token. Please read email carefully and try again.',
];

$config['ERRORANDREQUIREDMSG']=[
    1=>'Email is required.',
    2=>'Password is required',
    3=>'Current password is required.',
    4=>'New password is required.',
    5=>'Confirm password is required.',
    6=>'All fields are required.',
    7=>'Missing required information. Please read email carefully and try again.',
];